name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: Run tests with pytest
        run: |
          mkdir artifacts
          mkdir -p test/data
          pytest -v | tee artifacts/test_output.txt
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: test_artifacts
          path: artifacts
